// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../sburyv1Schema';

export const PaymentconfirmationsSchema = {
  entity: 'payment_confirmations',

  moduleRole: 'view_payment_confirmations',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'result_type', type: 'text', searchable: true },
    { key: 'result_code', type: 'text', title: true, searchable: true },
    { key: 'result_desc', type: 'text', searchable: true },
    { key: 'originator_conversation_id', type: 'text', searchable: true },
    { key: 'conversation_id', type: 'text', searchable: true },
    { key: 'transaction_id', type: 'text', searchable: true },
    { key: 'transaction_amount', type: 'money' },
    { key: 'transaction_receipt', type: 'textarea', searchable: true },
    { key: 'recipient_registered', type: 'text', searchable: true },
    { key: 'charges_paid_funds', type: 'text', searchable: true },
    { key: 'receiver_public_name', type: 'text', title: true, searchable: true },
    { key: 'transaction_date_time', type: 'datetime' },
    { key: 'utility_funds', type: 'text', searchable: true },
    { key: 'working_funds', type: 'text', searchable: true },
    { key: 'queue_timeout_url', type: 'text', searchable: true },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('site_id', { key: 'hive_site_id', as: 'site_name' }),
  },

  roles: { view: 'view_paymentconfirmations', manage: 'manage_paymentconfirmations' },
};
