// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../sburyv1Schema';

export const ExpensesSchema = {
  entity: 'expenses',

  moduleRole: 'view_expenses',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'expense_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'expense_category', type: 'text', searchable: true },
    { key: 'rate', type: 'text', searchable: true },
    { key: 'quantity', type: 'text', searchable: true },
    { key: 'ref_no', type: 'text', searchable: true },
    { key: 'expense_remark', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'site_id', type: 'text', searchable: true },
    { key: 'expense_date', type: 'datetime' },
    { key: 'week_no', type: 'money' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'subcontracor', type: 'text', searchable: true },
    { key: 'staff', type: 'text', searchable: true },
    { key: 'admin', type: 'text', searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('site_id', { as: 'site_name' }),
    ...resolveJoin('subcontracor', { as: 'name' }),
    ...resolveJoin('staff', { as: 'name' }),
    ...resolveJoin('admin', { as: 'name' }),
  },

  roles: { view: 'view_expenses', manage: 'manage_expenses' },
};
