// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../sburyv1Schema';

export const AttendanceSchema = {
  entity: 'attendance_list',

  moduleRole: 'view_attendance_list',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'name', type: 'text', title: true, required: true, searchable: true },
    { key: 'mobile', type: 'text', searchable: true },
    { key: 'national_id', type: 'text', searchable: true },
    { key: 'daily_wages', type: 'text', searchable: true },
    { key: 'remark', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'paid_status', type: 'text', searchable: true },
    { key: 'paid_ref_no', type: 'text', searchable: true },
    { key: 'site_id', type: 'text', searchable: true },
    { key: 'site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'date_paid', type: 'datetime' },
    { key: 'roll_date', type: 'datetime' },
    { key: 'day_count', type: 'text', computed: true, sum: true, searchable: true },
    { key: 'deductions', type: 'text', searchable: true },
    { key: 'deduction_remark', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'task_assigned', type: 'text', searchable: true },
    { key: 'project_phase', type: 'text', searchable: true },
    { key: 'sitetest', type: 'text', searchable: true },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('site_id', { as: 'site_name' }),
    ...resolveJoin('site_id', { key: 'hive_site_id', as: 'site_name' }),
  },

  roles: { view: 'view_attendance', manage: 'manage_attendance' },
};
