// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../sburyv1Schema';

export const PaybilldisbursmentsSchema = {
  entity: 'paybill_disbursments',

  moduleRole: 'view_paybill_disbursments',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'trxkey', type: 'text', system: true, editable: false },
    { key: 'trx_id', type: 'text', searchable: true },
    { key: 'trx_date', type: 'datetime' },
    { key: 'trx_month_year', type: 'text', searchable: true },
    { key: 'trx_remark', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'amount', type: 'text', searchable: true },
    { key: 'trx_type', type: 'text', searchable: true },
    { key: 'business_id', type: 'text', searchable: true },
    { key: 'client_id', type: 'text', searchable: true },
    { key: 'admin_id', type: 'text', searchable: true },
    { key: 'TransactionType', type: 'text', searchable: true },
    { key: 'BusinessShortCode', type: 'text', searchable: true },
    { key: 'BillRefNumber', type: 'text', searchable: true },
    { key: 'InvoiceNumber', type: 'text', searchable: true },
    { key: 'OrgAccountBalance', type: 'money' },
    { key: 'ThirdPartyTransID', type: 'text', searchable: true },
    { key: 'MSISDN', type: 'text', searchable: true },
    { key: 'FirstName', type: 'text', searchable: true },
    { key: 'MiddleName', type: 'text', searchable: true },
    { key: 'LastName', type: 'text', searchable: true },
    { key: 'trx_msg', type: 'text', searchable: true },
    { key: 'account_id', type: 'text', searchable: true },
    { key: 'used_status', type: 'text', searchable: true },
    { key: 'filter_date', type: 'datetime' },
    { key: 'flw_id', type: 'text', searchable: true },
    { key: 'flag_state', type: 'text', searchable: true },
    { key: 'reconciled', type: 'text', searchable: true },
    { key: 'trx_timestamp', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('site_id', { key: 'hive_site_id', as: 'site_name' }),
  },

  roles: { view: 'view_paybilldisbursments', manage: 'manage_paybilldisbursments' },
};
