// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../sburyv1Schema';

export const CashdepositsSchema = {
  entity: 'cash_deposits',

  moduleRole: 'view_cash_deposits',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'postkey', type: 'text', system: true, editable: false },
    { key: 'amount_posted', type: 'money' },
    { key: 'posted_by', type: 'text', searchable: true },
    { key: 'date_posted', type: 'datetime' },
    { key: 'posting_remark', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'admin_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'project_id', type: 'text', searchable: true },
    { key: 'project_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('posted_by', { as: 'name' }),
    ...resolveJoin('project_id', { as: 'site_name' }),
  },

  roles: { view: 'view_cashdeposits', manage: 'manage_cashdeposits' },
};
