// sburyv1Schema.js
// -------------------------------------------------------------------
// AUTO-GENERATED by schemamap.js from app\sburyv1\schemamap.txt — do not hand-edit
// the globalRelations object below. Edit the spec file and rerun:
//   node schemamap.js
//
// Column name on a specific module differs from the relation key (e.g.
// a polymorphic "__" key, or a renamed FK column) — pass 'key' in
// overrides so both sides stay in sync.
// Override ANYTHING else per-module the same way — second arg always
// wins, shallow merge over the global default.
// Unknown relation key throws instead of silently returning undefined
// (fail loud, not silent).
//
// endpoint (frontend only) resolves live via apiRoutes.json/getApiRoutes,
// keyed by table.replace(/_/g, '') — the SAME default routeKey db-cli.js
// writes when it builds that table's own schema.js. If that table's
// schema was built with a custom --list-name prefix, its real
// apiRoutes.json key won't match this guess — hand-fix that one entry's
// endpoint here (or re-point it at a literal string) rather than
// regenerating; schemamap.js has no way to know about a prefix chosen in
// a different tool's run.
// -------------------------------------------------------------------

export const globalRelations = {

  admin: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: expenses, payment_receivers
  },

  bundle_id: {
    table: "system_role_bundles",
    valueField: "record_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Role Bundle",
    // used by: user_bundle_role_functions
  },

  contact_id: {
    table: "phonebook",
    valueField: "contact_id",
    displayField: "name",
    cacheField: "name",
    label: "Contact",
    // used by: send_list
  },

  contact_person: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: site_list
  },

  expense_id: {
    table: "expenses",
    valueField: "record_id",
    displayField: "expense_name",
    cacheField: "expense_name",
    label: "Expense",
    // used by: custom_payments, payment_receivers
  },

  posted_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: cash_deposits
  },

  project_id: {
    table: "site_list",
    valueField: "project_id",
    displayField: "site_name",
    cacheField: "site_name",
    label: "Project",
    // used by: custom_payments, disbursment_schedule
  },

  receiver_id: {
    table: "staff",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "Staff",
    // used by: custom_payments
  },

  ref_id: {
    table: "system_role_bundles",
    valueField: "bundle_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Role",
    // used by: system_users
  },

  role_id: {
    table: "system_role_bundles",
    valueField: "record_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Role Bundle",
    // used by: user_manifest_
  },

  schedule_id: {
    table: "disbursment_schedule",
    valueField: "record_id",
    displayField: "remark",
    cacheField: "remark",
    label: "Disbursement Schedule",
    // used by: payment_receivers
  },

  signature_id: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: custom_payments
  },

  site_id: {
    table: "site_list",
    valueField: "record_id",
    displayField: "site_name",
    cacheField: "site_name",
    label: "Site",
    // used by: attendance_list, expenses, phonebook, send_list, staff, user_manifest_, user_site_allocation, work_schedule
  },

  staff: {
    table: "staff",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "Staff",
    // used by: expenses
  },

  staff_id: {
    table: "staff",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "Staff",
    // used by: payment_receivers
  },

  staff_role: {
    table: "staff_categories",
    valueField: "record_id",
    displayField: "work_title",
    cacheField: "work_title",
    label: "Role / Skill",
    // used by: staff
  },

  subcontracor: {
    table: "contractors",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "Contractor",
    // used by: expenses
  },

  user_id: {
    table: "system_users",
    valueField: "user_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: user_manifest_, user_site_allocation
  },

};

function cacheKeyFor(rel, columnKey) {
  return `_${rel.table}_${rel.cacheField}_${columnKey}`;
}

function getRelation(relationKey, fnName) {
  const rel = globalRelations[relationKey];
  if (!rel) {
    throw new Error(
      `${fnName}: no globalRelations entry for "${relationKey}". ` +
      `Regenerate from schemamap.txt, or define this field/join locally instead.`
    );
  }
  return rel;
}

// Use it on the BACKEND schema (in 'batchMutations:'):
//     ...resolveJoin('staff_id')
//     ...resolveJoin('related_record_id__app_users', { key: 'related_record_id' })
//
// Cache alias too long/ugly (e.g. "_fuel_stations_station_name_fuel_station_id")?
// Override it with 'as' — pass the SAME 'as' value to resolveField on the
// frontend side so the two stay pointed at the same column on the row:
//     ...resolveJoin('fuel_station_id', { as: 'station_name' })
export function resolveJoin(relationKey, overrides = {}) {
  const rel = getRelation(relationKey, 'resolveJoin');
  const columnKey = overrides.key || relationKey;
  const cacheKey = overrides.as || cacheKeyFor(rel, columnKey);
  const descriptor = {
    type: 'join',
    table: rel.table,
    link: `${columnKey}:${rel.valueField}`,
    select: { [cacheKey]: rel.cacheField },
  };
  const { key: _unusedKey, as: _unusedAs, ...restOverrides } = overrides;
  return { [cacheKey]: { ...descriptor, ...restOverrides } };
}

// ---------------------------------------------------------------------
// Detected "reverse" relations (record_id referenced FROM another table).
// These are candidate multiGridRows / child-grid wiring, NOT parent
// lookups, so they are not turned into resolveField/resolveJoin entries.
// Wire manually into multiGridRows on the parent module's schema.js.
// ---------------------------------------------------------------------
// (none detected in this spec)
