// sburyv1Schema.js
// -------------------------------------------------------------------
// AUTO-GENERATED by schemamap.js from app\sburyv1\schemamap.txt — do not hand-edit
// the globalRelations object below. Edit the spec file and rerun:
//   node schemamap.js
//
// Column name on a specific module differs from the relation key (e.g.
// a polymorphic "__" key, or a renamed FK column) — pass 'key' in
// overrides so both sides stay in sync.
// Override ANYTHING else per-module the same way — second arg always
// wins, shallow merge over the global default.
// Unknown relation key throws instead of silently returning undefined
// (fail loud, not silent).
//
// endpoint (frontend only) resolves live via apiRoutes.json/getApiRoutes,
// keyed by table.replace(/_/g, '') — the SAME default routeKey db-cli.js
// writes when it builds that table's own schema.js. If that table's
// schema was built with a custom --list-name prefix, its real
// apiRoutes.json key won't match this guess — hand-fix that one entry's
// endpoint here (or re-point it at a literal string) rather than
// regenerating; schemamap.js has no way to know about a prefix chosen in
// a different tool's run.
// -------------------------------------------------------------------

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
const apiRoute = getApiRoutes();

export const globalRelations = {

  admin: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: expenses, payment_receivers
  },

  bundle_id: {
    table: "system_role_bundles",
    endpoint: apiRoute.systemrolebundles.base,
    valueField: "record_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Role Bundle",
    // used by: user_bundle_role_functions
  },

  contact_id: {
    table: "phonebook",
    endpoint: apiRoute.phonebook.base,
    valueField: "contact_id",
    displayField: "name",
    cacheField: "name",
    label: "Contact",
    // used by: send_list
  },

  contact_person: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: site_list
  },

  expense_id: {
    table: "expenses",
    endpoint: apiRoute.expenses.base,
    valueField: "record_id",
    displayField: "expense_name",
    cacheField: "expense_name",
    label: "Expense",
    // used by: custom_payments, payment_receivers
  },

  posted_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: cash_deposits
  },

  project_id: {
    table: "site_list",
    endpoint: apiRoute.sitelist.base,
    valueField: "project_id",
    displayField: "site_name",
    cacheField: "site_name",
    label: "Project",
    // used by: custom_payments, disbursment_schedule
  },

  receiver_id: {
    table: "staff",
    endpoint: apiRoute.staff.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "Staff",
    // used by: custom_payments
  },

  ref_id: {
    table: "system_role_bundles",
    endpoint: apiRoute.systemrolebundles.base,
    valueField: "bundle_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Role",
    // used by: system_users
  },

  role_id: {
    table: "system_role_bundles",
    endpoint: apiRoute.systemrolebundles.base,
    valueField: "record_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Role Bundle",
    // used by: user_manifest_
  },

  schedule_id: {
    table: "disbursment_schedule",
    endpoint: apiRoute.disbursmentschedule.base,
    valueField: "record_id",
    displayField: "remark",
    cacheField: "remark",
    label: "Disbursement Schedule",
    // used by: payment_receivers
  },

  signature_id: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: custom_payments
  },

  site_id: {
    table: "site_list",
    endpoint: apiRoute.sitelist.base,
    valueField: "record_id",
    displayField: "site_name",
    cacheField: "site_name",
    label: "Site",
    // used by: attendance_list, expenses, phonebook, send_list, staff, user_manifest_, user_site_allocation, work_schedule
  },

  staff: {
    table: "staff",
    endpoint: apiRoute.staff.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "Staff",
    // used by: expenses
  },

  staff_id: {
    table: "staff",
    endpoint: apiRoute.staff.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "Staff",
    // used by: payment_receivers
  },

  staff_role: {
    table: "staff_categories",
    endpoint: apiRoute.staffcategories.base,
    valueField: "record_id",
    displayField: "work_title",
    cacheField: "work_title",
    label: "Role / Skill",
    // used by: staff
  },

  subcontracor: {
    table: "contractors",
    endpoint: apiRoute.contractors.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "Contractor",
    // used by: expenses
  },

  user_id: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "user_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: user_manifest_, user_site_allocation
  },

};

function cacheKeyFor(rel, columnKey) {
  return `_${rel.table}_${rel.cacheField}_${columnKey}`;
}

function getRelation(relationKey, fnName) {
  const rel = globalRelations[relationKey];
  if (!rel) {
    throw new Error(
      `${fnName}: no globalRelations entry for "${relationKey}". ` +
      `Regenerate from schemamap.txt, or define this field/join locally instead.`
    );
  }
  return rel;
}

// ALWAYS returns an array — spread it into fields: every time, even when
// you're only expecting one field back. Consistent shape regardless of
// arguments means you can never forget the spread and end up with a stray
// nested array sitting inside fields: (which would silently corrupt the
// module — arrays aren't valid field entries).
//
//     ...resolveField('staff_id')
//     ...resolveField('related_record_id__app_users', { key: 'related_record_id', label: 'User Profile' })
//
// Pass 'as' to ALSO get a second, plain display field for the cached
// value itself — e.g. so "station_name" shows up in showInList/sections
// as its own field, not just as the liveSearch dropdown's hidden cache.
// Third arg overrides that second field (key/label/type/title/required/
// anything) — defaults to a read-only text field if you don't:
//
//     ...resolveField('fuel_station_id', { as: 'station_name' }, { label: 'Station Name', title: true, required: true })
//     -> [ { key: 'fuel_station_id', type: 'liveSearch', ... },
//          { key: 'station_name', label: 'Station Name', type: 'text', title: true, required: true } ]
//
// Pass the SAME 'as' value to resolveJoin on the backend side so both
// stay pointed at the same cached column on the row.
export function resolveField(relationKey, overrides = {}, displayOverrides = {}) {
  const rel = getRelation(relationKey, 'resolveField');
  const columnKey = overrides.key || relationKey;
  const cacheKey = overrides.as || cacheKeyFor(rel, columnKey);

  const { as: _unusedAs, ...restFieldOverrides } = overrides;
  const liveSearchField = {
    key: columnKey,
    label: rel.label,
    type: 'liveSearch',
    colSpan: 6,
    endpoint: rel.endpoint,
    searchTable: rel.table,
    valueField: rel.valueField,
    displayField: rel.displayField,
    labelKey: cacheKey,
    ...restFieldOverrides,
  };

  if (!overrides.as) {
    return [liveSearchField];
  }

  const cachedDisplayField = {
    key: cacheKey,
    label: rel.label,
    type: 'text',
    computed: true,
    editable: false,
    ...displayOverrides,
  };

  return [liveSearchField, cachedDisplayField];
}

// ---------------------------------------------------------------------
// Detected "reverse" relations (record_id referenced FROM another table).
// These are candidate multiGridRows / child-grid wiring, NOT parent
// lookups, so they are not turned into resolveField/resolveJoin entries.
// Wire manually into multiGridRows on the parent module's schema.js.
// ---------------------------------------------------------------------
// (none detected in this spec)
