// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../sburyv1Schema';

export const StaffSchema = {
  entity: 'staff',

  moduleRole: 'view_staff',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'name', type: 'text', title: true, required: true, searchable: true },
    { key: 'mobile', type: 'text', searchable: true },
    { key: 'national_id', type: 'text', searchable: true },
    { key: 'daily_wages', type: 'money' },
    { key: 'staff_role', type: 'text', searchable: true },
    { key: 'site_id', type: 'text', searchable: true },
    { key: 'allocated_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'notification_number', type: 'text', searchable: true },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('staff_role', { as: 'work_title' }),
    ...resolveJoin('site_id', { as: 'site_name' }),
  },

  roles: { view: 'view_staff', manage: 'manage_staff' },
};
